# Task 1: Creating and Manipulating Arrays
##### Create a 1-dimensional NumPy array with 10 elements of your choice.
##### Create a 2-dimensional NumPy array with shape (3, 4) containing random integers between 1 and 20.
##### Reshape the 2D array into a 4x3 array and then into a 1D array.
##### Slice the first 5 elements from the 1D array you created and print them.
##### Create an array of zeros with shape (2, 3) and another array of ones with shape (3, 2).

In [29]:
import numpy as np
#Create a 1-dimensional NumPy array with 10 elements of your choice.

array1 = np.array([3, 7, 1, 9, 4, 6, 2, 8, 5, 10])
array

array([ 3,  7,  1,  9,  4,  6,  2,  8,  5, 10])

In [3]:
#Create a 2-dimensional NumPy array with shape (3, 4) containing random integers between 1 and 20.

array2 = np.random.randint(1, 21, size=(3, 4))
array2

array([[11, 10,  9, 10],
       [ 8,  4, 18,  5],
       [15, 11,  4, 17]])

In [10]:
#Reshape the 2D array into a 4x3 array and then into a 1D array.

array3 = array2.reshape(4,3)
print(array3)

array4 = array3.ravel()
print(array4)

[[11 10  9]
 [10  8  4]
 [18  5 15]
 [11  4 17]]
[11 10  9 10  8  4 18  5 15 11  4 17]


In [12]:
#Slice the first 5 elements from the 1D array you created and print them.
print(array4[:5])

[11 10  9 10  8]


In [16]:
#Create an array of zeros with shape (2, 3) and another array of ones with shape (3, 2).

print("Below contains array of zeros")
array_of_zeros = np.zeros((2,3))
print(array_of_zeros)

print("\n")
print("Below contains array of ones")
array_of_ones = np.ones((3,2))
print(array_of_ones)

Below contains array of zeros
[[0. 0. 0.]
 [0. 0. 0.]]


Below contains array of ones
[[1. 1.]
 [1. 1.]
 [1. 1.]]


## Task 2: Array Operations
##### Perform element-wise addition, subtraction, multiplication, and division on two arrays of your choice.
##### Compute the dot product of two 2D arrays (of compatible shapes) and print the result.
##### Create a 3x3 identity matrix using NumPy functions.
##### Calculate the sum, mean, standard deviation, and variance of a 1D array.

In [19]:
#Perform element-wise addition, subtraction, multiplication, and division on two arrays of your choice.

# Creating two arrays for element-wise operations
array_one = np.array([5, 10, 15, 20])
array_two = np.array([2, 4, 6, 8])

# Performing element-wise operations
addition = array_one + array_two
subtraction = array_one - array_two
multiplication = array_one * array_two
division = array_one / array_two

addition, subtraction, multiplication, division


(array([ 7, 14, 21, 28]),
 array([ 3,  6,  9, 12]),
 array([ 10,  40,  90, 160]),
 array([2.5, 2.5, 2.5, 2.5]))

In [25]:
#Compute the dot product of two 2D arrays (of compatible shapes) and print the result.

# Creating two 2D arrays for dot product calculation
array_dot_one = np.array([[1, 2, 3], [4, 5, 6]])
print(array_dot_one)
array_dot_two = np.array([[7, 8], [9, 10], [11, 12]])
print(array_dot_two)

# Computing the dot product
dot_product = np.dot(array_dot_one, array_dot_two)
dot_product


[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


array([[ 58,  64],
       [139, 154]])

In [27]:
#Create a 3x3 identity matrix using NumPy functions

array_identity = np.identity(3)
print(array_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
#Calculate the sum, mean, standard deviation, and variance of a 1D array
#Recall the first array created
print(array1)

array_sum = np.sum(array1)
array_mean = np.mean(array1)
array_std = np.std(array1)
array_variance = np.var(array1)
print(f"Sum : {array_sum}")
print(f"Mean : {array_mean}")
print(f"Std : {array_std}")
print(f"Variance : {array_variance}")

[ 3  7  1  9  4  6  2  8  5 10]
Sum : 55
Mean : 5.5
Std : 2.8722813232690143
Variance : 8.25


### Task 3: Boolean Indexing and Filtering
##### Create a 1D array with 15 random integers between 0 and 50.
##### Use Boolean indexing to filter out all elements greater than 25 and print the result.
##### Replace all values in the array that are less than 10 with 10.

In [42]:
#Create a 1D array with 15 random integers between 0 and 50.

array_random = np.random.randint(0, 50, size=15)
print(len(array_random))
array_random

15


array([47, 28, 22, 31, 30, 36, 33, 14, 25, 27, 26, 10, 42,  6, 46])

In [43]:
#Use Boolean indexing to filter out all elements greater than 25 and print the result.
print(array_random[array_random > 25])

[47 28 31 30 36 33 27 26 42 46]


In [44]:
#Replace all values in the array that are less than 10 with 10.
array_random[array_random < 10] = 10
print(array_random)

[47 28 22 31 30 36 33 14 25 27 26 10 42 10 46]


### Task 4: Advanced Operations
##### Generate a 5x5 matrix with random integers and find the minimum and maximum values in the matrix.
##### Calculate the row-wise and column-wise sums of the matrix.
##### Create two 2D arrays and stack them vertically and horizontally using NumPy functions

In [52]:
#Generate a 5x5 matrix with random integers and find the minimum and maximum values in the matrix.

array_random_matrix = np.random.randint(0, 50, size=(5,5))
# print(len(array_random_matrix))
print(array_random_matrix)
print(f"Max value = {np.max(array_random_matrix)}")
print(f"Min value = {np.min(array_random_matrix)}")

[[ 7 31 13 13 16]
 [ 8 42  1 34 13]
 [48 26 20 20 48]
 [31 21 10 13  9]
 [28  8  4 10 15]]
Max value = 48
Min value = 1


In [53]:
#Calculate the row-wise and column-wise sums of the matrix.
# Calculate the row-wise sums
row_sums = np.sum(array_random_matrix, axis=1)

# Calculate the column-wise sums
column_sums = np.sum(array_random_matrix, axis=0)

print("Row-wise sums:", row_sums)
print("Column-wise sums:", column_sums)

Row-wise sums: [ 80  98 162  84  65]
Column-wise sums: [122 128  48  90 101]


In [56]:
#Create two 2D arrays and stack them vertically and horizontally using NumPy functions.

# Create two 2D arrays
array_stack_1 = np.array([[1, 2], [3, 4]])
arraystack_2 = np.array([[5, 6], [7, 8]])

# Stack the arrays vertically
vertical_stack = np.vstack((array_stack_1, arraystack_2))

# Stack the arrays horizontally
horizontal_stack = np.hstack((array_stack_1, arraystack_2))

print(f"Vertical Stack:\n {vertical_stack}")
print(f"Horizontal Stack:\n {horizontal_stack}")


Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]
